# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17d756e53817065a5d3a823ebc1bbb3b9b3a8e777824d8c411c81e9783162958b04892c18b0c0628ffbfaed6d5dd70ef1cd3bd617bcdc26dc5d66e75c048ecc0

test:
  secret_key_base: 5bb0c52fddee32b4c269516c402cc378b03e2670d3a68e106092f8bb85383dfeec30a83d77800090b01b837e08c594fed91a78b13f91934945a3811decadafcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
