# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1867d5ecb96d5f74ac47a3402cfb3d3d8dad68163577a3a4327c9f4ba33bc29eb114dbee0e56fb45805523c7ed7ba669fcc09dbe78cd37b7fb565109dcdd439

test:
  secret_key_base: 3b5680033d440d6449658cfea18a62daf985283f91e6e226688dec1a75737b23cbf21213ecf25b218e0be434e00203d03b587d2523e03dd4f28646221695e828

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
